# Generated by Django 5.0.6 on 2024-06-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='izakaya',
        ),
        migrations.AddField(
            model_name='listitem',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listitem',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listitem',
            name='name',
            field=models.CharField(default=0.0, max_length=255),
            preserve_default=False,
        ),
    ]
